### ISSUE TITLE
meta issue to track workshop websites that need to be updated

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/lesson-infrastructure#28]
- [x] https://github.com/swc-mizzou/2020-05-07-mizzou
- [x] https://github.com/SADiLaR/2020-05-05-SA-ONLINE
- [x] https://github.com/carpentries-uconn/2020-05-01-UConn-online
- [x] https://github.com/qcif-training/2020-04-30-QCIF-R
- [ ] https://github.com/amytrost/2020-04-30-rockville (no mention that it was online)
- [x] https://github.com/charlesincharge/2020-04-28-genentech
- [ ] https://github.com/BrockDSL/2020-04-29-Ryerson (no mention that it was online)
- [x] https://github.com/gu-eresearch/2020-04-27-GriffithUni-Python
- [ ] https://github.com/CurtinIC/2020-04-21-curtin
- [ ] ~~http://swc-bb.gitext.gfz-potsdam.de/edit//index.md~~
- [x] https://github.com/qcif-training/2020-04-20-QCIF-Python
- [x] https://github.com/escience-academy/2020-04-14-SWC-online
- [x] https://github.com/mbrousil/2020-04-13-wsu
- [x] https://ucla-data-archive.github.io/2020-04-10-ucla/
- [x] https://github.com/swc-mizzou/2020-04-09-mizzou
- [x] https://github.com/aschuerch/2020-04-06-Utrecht
- [ ] https://github.com/kaust-vislab/2020-04-01-kaust-vislab
- [x] https://github.com/GenomicsAotearoa/2020-03-31-online
- [ ] https://github.com/kaust-vislab/2020-03-30-kaust-vislab
- [x] https://github.com/qcif-training/2020-03-27-CQU-Unix
- [x] https://github.com/gwu-libraries/2020-03-26-carpentry
- [x] https://github.com/erichseamon/2020-03-26-uidaho-geospatial
- [ ] https://github.com/qcif-training/2020-03-23-UQ-Python

**Comment by Talishask** [comment]
Here is some info on the unchecked workshops:

**Tagged as online in AMY and online noted on workshop webpage**
- https://github.com/CurtinIC/2020-04-21-curtin

**No mention of online on the website, no cancellation notice via helpscout but no survey results, which suggests the event may have been cancelled:**
- https://github.com/amytrost/2020-04-30-rockville
- https://github.com/BrockDSL/2020-04-29-Ryerson (1 pre and no post results - likely cancelled)
- https://github.com/kaust-vislab/2020-04-01-kaust-vislab 
- https://github.com/kaust-vislab/2020-03-30-kaust-vislab (1 pre and no post results - likely cancelled)

**No mention of online on the website but survey results indicate the workshop took place:**
- https://github.com/qcif-training/2020-03-23-UQ-Python
